name: Vine Server - September Test

on:
  push:
    branches: [ "September" ]
  pull_request:
    branches: [ "September" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Setup Powershell
        run: |
          wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.5/powershell_7.4.5-1.deb_amd64.deb
          sudo dpkg -i powershell_7.4.5-1.deb_amd64.deb
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Configure Git User Details
        run: git config --global user.email "no-reply@tranic.one" && git config --global user.name "Vine Server"
      - name: Apply Patches
        run: gradle applyPatches
      - name: CreateJar
        run: gradle createMojmapPaperclipJar
      - name: SetENV
        run: pwsh scripts/SetEnv.ps1
      - name: Clear Build
        run: pwsh scripts/clear_build.ps1
      - name: Upload Artifact
        uses: "actions/upload-artifact@v4"
        with:
          name: "${{ env.project_id_b }} CI Artifacts"
          path: "build/libs/*.jar"
      - name: Create Release
        if: "!contains(github.event.commits[0].message, '[release skip]')"
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ env.tag }}
          name: ${{ env.project_id_b }} ${{ env.mcversion }} - ${{ env.commit_id }} (September Test)
          body: |
            📦Version: `${{ env.mcversion }} (September Test)` | Commit ${{ env.commit_id }} [![download](https://img.shields.io/github/downloads/LevelTranic/${{ env.project_id }}/${{ env.tag }}/total?color=red&style=flat-square)](https://github.com/LevelTranic/${{ env.project_id }}/download/${{ env.tag }}/${{ env.jar }})
            This release is automatically compiled by GitHub Actions 
            **In the September test version, please do not use it for production before the merger is merged to the main line!!!**
            **This version will not synchronize to API.**
            ### Commit Message
            ${{ env.commit_msg }}
          artifacts: |
            ${{ env.jar_dir }}
            ${{ env.jar_dir_bundler }}
          generateReleaseNotes: true
          prerelease: ${{ env.pre }}
          makeLatest: ${{ env.make_latest }}
          token: "${{ secrets.GITHUB_TOKEN }}"